/* // src/types/exam.ts
export type LangSpecificText = { [langKey: string]: string };
export type OptionValue = string | LangSpecificText; // Represents the actual value of an option

export interface Option { // This was defined before, ensure it aligns or is used if distinct from OptionValue
  id: string; // Unique ID for the option itself (e.g., 'opt_a')
  text: string | LangSpecificText; // The display text of the option
  value?: OptionValue; // Optional: if the stored value differs from display text or ID. Often, `id` or `text` itself is the value.
}

export interface Question {
  id: string; // Keep as string, consistent with Date.now().toString()
  type: 'multiple-choice' | 'open-ended';
  question: string | LangSpecificText; // Main question text

  // For multiple-choice questions
  // options?: Option[]; // Array of Option objects (more structured)
  // OR simpler OptionValue array if ids/complex structure not needed for options
  options?: OptionValue[]; // If options are just strings or LangSpecificText
  // OR if options are structured with IDs and text:
  // options?: { id: string; text: string | LangSpecificText }[];


  correctOptionId?: string; // ID of the correct Option (if using structured options with IDs)
  answerKey?: string | LangSpecificText; // For open-ended, or if correct MC answer is text-based
  explanation?: string | LangSpecificText;
}

export interface Exam {
  id: string;
  title: string;
  language?: {
    primary: string;
    secondary?: string;
  };
  questions: Question[];
  includeAnswerKey?: boolean; // Example of an additional exam-level property
}
 */

// src/types/exam.ts

// Defines a structure for text that can be a simple string or an object
// where keys are language codes (e.g., "en", "es") and values are strings.
export type LangSpecificText = {
  [langCode: string]: string;
};

// Defines the value of a selectable option or an answer key.
// It can be a simple string or a LangSpecificText object for multilingual values.
export type OptionValue = string | LangSpecificText;

// Interface for a single question within an exam.
export interface Question {
  id: string | number; // Unique identifier for the question (can be string or number from JSON).
  type: 'multiple-choice' | 'open-ended'; // Type of the question.
  domain?: string | null; // Optional domain/category for the question. Can be null or undefined.
  question: string | LangSpecificText; // The question text itself, can be multilingual.

  // Options for multiple-choice questions. Can be:
  // 1. An array of OptionValue (each option is string or LangSpecificText).
  // 2. An object where keys are language codes and values are arrays of simple strings.
  // 3. Null or undefined (especially for open-ended questions).
  options?: OptionValue[] | { [langCode: string]: string[] } | null;

  // The correct answer for the question. Can be string, LangSpecificText, null, or undefined.
  answerKey?: OptionValue | null;

  // Optional explanation for the question's answer, can be multilingual.
  explanation?: string | LangSpecificText | null;

  // Allows for other properties that might be dynamically added (e.g., userProvidedAnswer for exports).
  [key: string]: any;
}

// Interface for the main Exam structure.
export interface Exam {
  id: string; // Unique ID for the exam, generated by the app upon import.
  title: string; // Title of the exam.

  // Optional language settings for the exam.
  language?: {
    primary: string; // Primary language code (e.g., "en").
    secondary?: string; // Optional secondary language code.
  } | null;

  // Optional flag to indicate if the answer key should be included/used.
  includeAnswerKey?: boolean | null;

  questions: Question[]; // Array of questions.

  // Allows for other top-level properties in the exam object (e.g. resultSummary for exports).
  [key: string]: any;
}